

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: lazymail_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lazymail_network

  # Redis for queues and caching
  redis:
    image: redis:7-alpine
    container_name: lazymail_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lazymail_network

  # Rspamd spam/phishing detection
  rspamd:
    image: rspamd/rspamd:latest
    container_name: lazymail_rspamd
    ports:
      - "${RSPAMD_PORT}:11334"  # Controller port
      - "11333:11333"            # Normal worker port
    volumes:
      - ./infra/rspamd/local.d:/etc/rspamd/local.d
      - ./infra/rspamd/local.d/worker-controller.inc:/etc/rspamd/local.d/worker-controller.inc
      - rspamd_data:/var/lib/rspamd
    environment:
      - RSPAMD_PASSWORD=${RSPAMD_CONTROLLER_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11334/ping"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - lazymail_network

networks:
  lazymail_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rspamd_data:
