"""Initial schema with messages, verdicts, features

Revision ID: e16e0688ed64
Revises: 
Create Date: 2025-10-05 09:51:18.566325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16e0688ed64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=500), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=500), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('cc', sa.JSON(), nullable=True),
    sa.Column('bcc', sa.JSON(), nullable=True),
    sa.Column('reply_to', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=True),
    sa.Column('attachment_names', sa.JSON(), nullable=True),
    sa.Column('spf_result', sa.String(length=50), nullable=True),
    sa.Column('dkim_result', sa.String(length=50), nullable=True),
    sa.Column('dmarc_result', sa.String(length=50), nullable=True),
    sa.Column('received_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_account_id'), 'messages', ['account_id'], unique=False)
    op.create_index(op.f('ix_messages_analysis_status'), 'messages', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_messages_sender'), 'messages', ['sender'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('url_count', sa.Integer(), nullable=True),
    sa.Column('unique_domains', sa.Integer(), nullable=True),
    sa.Column('suspicious_tlds', sa.Integer(), nullable=True),
    sa.Column('url_shorteners', sa.Integer(), nullable=True),
    sa.Column('homograph_count', sa.Integer(), nullable=True),
    sa.Column('extracted_urls', sa.JSON(), nullable=True),
    sa.Column('body_length', sa.Integer(), nullable=True),
    sa.Column('html_to_text_ratio', sa.Float(), nullable=True),
    sa.Column('has_javascript', sa.Integer(), nullable=True),
    sa.Column('has_iframes', sa.Integer(), nullable=True),
    sa.Column('has_forms', sa.Integer(), nullable=True),
    sa.Column('urgent_words', sa.Integer(), nullable=True),
    sa.Column('financial_terms', sa.Integer(), nullable=True),
    sa.Column('personal_info_requests', sa.Integer(), nullable=True),
    sa.Column('avg_word_length', sa.Float(), nullable=True),
    sa.Column('sentence_count', sa.Integer(), nullable=True),
    sa.Column('exclamation_count', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('display_name_mismatch', sa.Integer(), nullable=True),
    sa.Column('reply_to_mismatch', sa.Integer(), nullable=True),
    sa.Column('received_hops', sa.Integer(), nullable=True),
    sa.Column('feature_vector', sa.JSON(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('verdicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('rspamd_score', sa.Float(), nullable=True),
    sa.Column('rspamd_action', sa.String(length=50), nullable=True),
    sa.Column('rspamd_symbols', sa.JSON(), nullable=True),
    sa.Column('auth_score', sa.Float(), nullable=True),
    sa.Column('url_score', sa.Float(), nullable=True),
    sa.Column('content_score', sa.Float(), nullable=True),
    sa.Column('stylometry_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('threat_indicators', sa.JSON(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyst_label', sa.String(length=50), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('analyst_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdicts_classification'), 'verdicts', ['classification'], unique=False)
    op.create_index(op.f('ix_verdicts_message_id'), 'verdicts', ['message_id'], unique=False)
    op.create_index(op.f('ix_verdicts_risk_score'), 'verdicts', ['risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdicts_risk_score'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_message_id'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_classification'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_table('features')
    op.drop_index(op.f('ix_messages_sender'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_analysis_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_account_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
